name: CI
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: i686-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install rust target ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --verbose --target ${{ matrix.target }}
      - name: Run tests
        run: cargo test --verbose --target ${{ matrix.target }}
