name: CI
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: i686-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4

      - name: Install gcc-multilib
        run: sudo apt-get update && sudo apt-get install gcc-multilib

      - name: Install rust target ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}

      - name: build
        uses: ./.github/actions/build
        with:
          TARGET: '${{ matrix.TARGET }}'

      - name: test
        uses: ./.github/actions/test
        with:
          TARGET: '${{ matrix.TARGET }}'

      - name: before_cache_script
        run: sudo rm -rf $CARGO_HOME/registry/index;
